### ISSUE TITLE
mod rejections Client need this mod ?

### ISSUE THREAD

**Issue by BuckTheWeasel** [felixlpge/MinecraftServerStartupDiscordAlert#1]
<img width="859" alt="error" src="https://user-images.githubusercontent.com/10898935/39121555-490c4db2-46f2-11e8-9e8a-b16f900420b8.PNG">

**Comment by strifel** [comment]
Oh I did not saw this issue. I think this Issue should be fixed since a few months.

**Comment by strifel** [comment]
Commit: 520dbd9f687ca36507d0bbb08694fa275bab77f9
